galleria_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# local app import
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('picasso/', include('picasso.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picasso/urls.py
from django.urls import path

# local imports
from picasso import views

app_name = 'picasso'  # app namespace
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('search/', views.search_results, name='search_results'),
    path('category/<str:category>/', views.get_by_category, name='get_by_category'),
]

picasso/models.py
import datetime
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField
# Create your models here.


class Category(models.Model):
    '''This Class defines the category model'''
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"Name: {self.name}"

    def save_category(self):
        '''method that saves the category'''
        self.save()

    def delete_category(self, id):
        '''method that deletes the category'''
        self.category = Category.objects.get(pk=id).delete()

    def update_category(self, id, name):
        '''method that update a particular category details'''
        try:
            self.category = Category.objects.filter(pk=id).update(name=name)
        except Exception as e:
            print('Error! unable to update category details: ', e)


class Location(models.Model):
    '''this classdefines the location model structure'''
    location_tag = models.CharField(default='Mars',
                                    max_length=50,  blank=True, unique=True)

    def __str__(self):
        return f"name: {self.location_tag}"

    def save_location(self):
        '''method that saves a location'''
        self.save()

    def delete_location(self, id):
        '''method that deletes a location tag'''
        self.location = Location.objects.get(pk=id).delete()

    def update_location(self, id, name):
        '''method that update a particular location tag'''
        try:
            self.location = Location.objects.filter(pk=id).update(location_tag=name)
        except Exception as e:
            print('Error! unable to update location details', e)


class Image(models.Model):
    """Class that defines the image data fields"""
    image_file = CloudinaryField('image')
    image_name = models.CharField(max_length=100, null=False)
    image_description = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    categories = models.ManyToManyField(Category)
    image_location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return f"Name: {self.image_name}"

    def was_published_recently(self):
        '''method to check if the question was published recently'''
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def save_image(self):
        '''method to save the selected image'''
        self.save()

    def delete_selected_image(self, id):
        '''method to delete the selected image'''
        try:
            self.image = Image.objects.filter(pk=id).delete()
        except Exception as e:
            print('Error: ', e)

    def update_image(self, image_name, image_description):
        '''method to update the selected image'''
        try:
            self.image = Image.objects.filter(id=self.id).update(
                image_name=image_name, image_description=image_description)
        except Exception as e:
            print("Error occured on update method: ", e)

    def search_image_by_category(self, category):
        '''method to search the image by category'''
        images = Image.objects.filter(categories__name__icontains=category)
        return images

    def filter_image_by_location(self, location):
        images = Image.objects.filter(image_location__location_tag__icontains=location)
        return images

galleria_project/views.py
from django.http import HttpResponse


# custom index view method
def index(request):
    return HttpResponse('<h1>Hello, Stranger!</h1> <a href="/picasso/">Picasso</a>')

picasso/views.py
from django.shortcuts import render

# LOCAL IMPORTS
from picasso.models import Image, Category, Location

# Create your views here.


def index(request):
    images = Image.objects.order_by('-pub_date')[:5]
    categories = Category.objects.all()
    location = Location.objects.all()
    context = {
        'images': images,
        'categories': categories,
        'location': location,
        'title': 'Home'
    }
    return render(request, 'picasso/index.html', context)


def about(request):
    context = {
        'title': 'About'
    }
    return render(request, 'picasso/about.html', context)


def search_results(request):
    categories = Category.objects.all()
    locations = Location.objects.all()

    if 'search_term' in request.GET and request.GET['search_term']:
        search_query = request.GET.get('search_term')
        searched_images = Image.search_image_by_category(
            '', search_query) or Image.filter_image_by_location('', search_query)
        message = f'Results for: {search_query}'
        context = {
            'images': searched_images,
            'categories': categories,
            'title': 'Search Results',
            'message': message
        }
        return render(request, 'picasso/index.html', context)
    else:
        message = 'No results found, Please try again.'
        return render(request, 'picasso/index.html', {'message': message})

# categories dropdown
def get_by_category(request, category):
    '''this method filters images by category picked by user'''
    categories = Category.objects.all()
    category_results = Image.search_image_by_category('', category)
    context = {
        'categories': categories,
        'images': category_results,
        'title': 'Categories'
    }
    return render(request, 'picasso/index.html', context)

picasso/templates/base.html
{% load bootstrap4 %} {% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% if title %}
    <title>Galleria |{{title}}</title>
    {% else %}
    <title>Galleria</title>
    {% endif %}

    <!-- static file links -->
    {% block styles %} {% bootstrap_css %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'picasso/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css"
    />

    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.15/css/mdb.min.css"
      rel="stylesheet"
    />
    {% endblock %}
    <!-- end static links -->
  </head>
  <body>
    {% include 'picasso/navbar.html' %}
    <div class="container">
      {% block content %}
      <!-- home content -->
      {%endblock%}
    </div>

    {% block scripts %}
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    {% bootstrap_javascript %}
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.15/js/mdb.min.js"
    ></script>
    <script src="{% static 'picasso/script.js' %}"></script>
    {% endblock %}
  </body>
</html>

picasso/templates/picasso/about.html
{% extends 'base.html' %}

<!-- about page -->
{% block content %}
<div>
  <h3>About</h3>
</div>
{% endblock %}
<!-- about page end -->
`

picasso/templates/picasso/index.html
{% extends 'base.html' %}

<!-- root view -->
{% block content %}
<div class="row">
  <!-- <div class="col-md-12 bg-info m-2 p-4">
    <h3 class="text-center">Aesthetes Chill spot.</h3>
  </div> -->
  <div class="mt-4">
    <!-- display all images -->
    <h3 class="h3">{{message}}</h3>
    <div class="col-md-12">
      <div class="card-columns">
        {% for image in images %}
        <div class="card">
          <a
            href="{{image.image_file.url}}"
            class="data-fancybox"
            data-fancybox="gallery"
            data-caption="
            <div class='fancy-text'>
              <strong class='image_name'>{{ image.image_name }}</strong>
              <small class='text-muted'>{{ image.pub_date}}</small>
              
              <p class='img-description'>{{ image.image_description }}</p>
              <small class=''>Location: {{image.image_location.location_tag}} &#9432;</small>
            </div>"
          >
            <img
              src="{{ image.image_file.url }}"
              alt="{{ image.image_name }} image"
              class="rounded"
            />
          </a>
          <small
            class="link-btn"
            data-toggle="tooltip"
            data-placement="top"
            title="copy image url"
            data-url="{{image.image_file.url}}"
            ><i class="fas fa-link"></i
          ></small>
        </div>
        {% endfor %}
      </div>

      <!-- todo: display image category -->
    </div>
  </div>
</div>
{% endblock %}

picasso/templates/picasso/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'picasso/style.css' %}" />
<!-- load css file -->

<div class="container mt-2">
  <nav class="navbar navbar-expand-lg top__nav rounded">
    <a class="navbar-brand logo" href="{% url 'picasso:index' %}">G.</a>
    <button
      class="navbar-toggler btn-outline-info"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon mt-1">|||</span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'picasso:index' %}"
            ><i class="fas fa-home"></i>
            <span class="sr-only">(current)</span></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'picasso:about' %}">About</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-expanded="false"
          >
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in categories %}
            <a
              class="dropdown-item"
              href="{% url 'picasso:get_by_category' category.name %}"
              >{{ category.name }}</a
            >
            {% endfor %}
            <div class="dropdown-divider"></div>
          </div>
        </li>
      </ul>
      <form
        class="form-inline my-2 my-lg-0"
        action="{% url 'picasso:search_results' %}"
      >
        <div class="input-group mb-2 mr-sm-2">
          <input
            class="form-control"
            type="search"
            name="search_term"
            placeholder="Search for anything..."
            aria-label="Search"
          />
          <div class="input-group-prepend">
            <div class="input-group-text">
              <button class="search_btn">
                <i class="fas fa-magnifying-glass"></i>
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </nav>
</div>